// [ @DisplayName, @Kitname, @CountPerSquad ]
dzn_zas_defaultKitIcon = 'A3\ui_f\data\map\markers\military\dot_CA.paa';

dzn_zas_kitList = [
	["NATO Squad Leader", "kit_BLUFOR_NATO_SquadLeader",		1, 'A3\ui_f\data\map\markers\military\triangle_CA.paa']
	,["NATO Team Leader", "kit_BLUFOR_NATO_TeamLeader",		2, 'A3\ui_f\data\map\markers\military\triangle_CA.paa']
	,["NATO Combat Life Saver", "kit_BLUFOR_NATO_CombatLifeSaver",	1, 'A3\ui_f\data\map\markers\military\triangle_CA.paa']
	,["NATO Automatic Rifleman", "kit_BLUFOR_NATO_Autorifleman",	2]	
	,["NATO Grenadier", "kit_BLUFOR_NATO_Grenadier",			1]
	,["NATO Rifleman (AT)", "kit_BLUFOR_NATO_RiflemanAT",		1]
	,["NATO AT Specialist", "kit_BLUFOR_NATO_MissileSpecialistAT",		1]	
	,["NATO Rifleman", "kit_BLUFOR_NATO_Rifleman",			6]
	,["NATO Crewman", "kit_BLUFOR_NATO_Crewman",			12]
	,["NATO Helicopter Pilot", "kit_BLUFOR_NATO_HelicopterPilot", 12]	
	
	,["FIA Squad Leader", "kit_BLUFOR_FIA_SquadLeader", 0]
	,["FIA Team Leader", "kit_BLUFOR_FIA_TeamLeader", 0]
	,["FIA Combat Life Saver", "kit_BLUFOR_FIA_CombatLifeSaver", 0]
	,["FIA Automatic Rifleman", "kit_BLUFOR_FIA_Autorifleman", 0]
	,["FIA Grenadier", "kit_BLUFOR_FIA_Grenadier", 0]
	,["FIA Rifleman (AT)", "kit_BLUFOR_FIA_RiflemanAT", 0]
	,["FIA Marksman", "kit_BLUFOR_FIA_Marksman", 0]
	,["FIA Rifleman", "kit_BLUFOR_FIA_Rifleman", 0]
	,["FIA Explosives Specicalist", "kit_BLUFOR_FIA_ExplosiveSpecialist", 0]
	
	,["AAF Squad Leader", "kit_INDEP_AAF_SquadLeader", 0]
	,["AAF Team Leader", "kit_INDEP_AAF_TeamLeader", 0]
	,["AAF Combat Life Saver", "kit_INDEP_AAF_CombatLifeSaver", 0]
	,["AAF Automatic Rifleman", "kit_INDEP_AAF_Autorifleman", 0]
	,["AAF Grenadier", "kit_INDEP_AAF_Grenadier", 0]
	,["AAF Rifleman (AT)", "kit_INDEP_AAF_RiflemanAT", 0]
	,["AAF AT Specialist", "kit_INDEP_AAF_MissileSpecialistAT", 0]
	,["AAF Rifleman", "kit_INDEP_AAF_Rifleman", 0]
	,["AAF Crewman", "kit_INDEP_AAF_Crewman", 0]
	,["AAF Helicopter Pilot", "kit_INDEP_AAF_HelicopterPilot", 0]
];
